:arrow_down: Revert upgrade to typechain packages to avoid bug
lib/generated/typechain-types/factories/artifacts/contracts/index.ts:7:13 - error TS1214: Identifier expected. 'interface' is a reserved word in strict mode. Modules are automatically in strict mode.

7 export * as interface from "./interface";